### ISSUE TITLE
saya dapat error nih, fixnya gmn yah :"

### ISSUE THREAD

**Issue by accusitivedev** [HirziDevs/discordjs-13-handler#1]
```bash
C:\Users\USER\Documents\desakulab\bot\DesakuExtra\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (C:\Users\USER\Documents\desakulab\bot\DesakuExtra\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\USER\Documents\desakulab\bot\DesakuExtra\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ApplicationCommandPermissionsManager.set (C:\Users\USER\Documents\desakulab\bot\DesakuExtra\node_modules\discord.js\src\managers\ApplicationCommandPermissionsManager.js:186:18)
    at async Timeout._onTimeout (C:\Users\USER\Documents\desakulab\bot\DesakuExtra\index.js:65:13) {
  method: 'put',
  path: '/applications/995534335602073621/guilds/952698353806897212/commands/permissions',
  code: 0,
  httpStatus: 405,
  requestData: { json: [], files: [] }
}

Node.js v17.2.0
```

**Comment by HirziDevs** [comment]
Bot nya gk ada token, telat 1 tahun coy
